name: release
on:
  push
#  release:
#    types: [published]

jobs:
  release:
    if: github.repository == 'demitchell14/CryptDocs'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn

      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> .npmrc
#          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: setup git...
        run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cryptdocs-client-v*.*.*
