name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.repository == 'demitchell14/CryptDocs'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: setup git...
        run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"

      - name: Pack Release
        run: |
          yarn pack

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cryptdocs-client-v*.*.*
