name: release
on:
  release:
    types: [published]

jobs:
  release:
    if: github.repository == 'demitchell14/CryptDocs'
    runs-on: ubunto-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn

      - name: Create .npmrc
        run: |
          echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
#          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          node scripts/publish.js
